const routeNames = {
  home: "Home",
  resident: "Resident",
  guard: "Guard",
  admin: "Admin",
  // Resident Routes
  residentHome: "residentHome",
  residentBill: "residentBill",
  residentHelp: "residentHelp",
  emergencyButton: "emergencyButton",
  emergencyForm: "emergencyForm",
  emergencyCancel: "emergencyCancel",
  residentVisitors: "residentVisitors",
  visitorMain: "visitorMain",
  visitorHistory: "visitorHistory",
  visitorAdded: "visitorAdded",
  residentNews: "residentNews",
  // Guard Routes
  guardHome: "guardHome",
  guardQrCode: "guardQrCode",
  guardQrCodeMain: "guardQrCodeMain",
  guardQrCodeScan: "guardQrCodeScan",
  guardQrCodeScanned: "guardQrCodeScanned",
  guardQrCodeHistory: "guardQrCodeHistory",
  guardVisitor: "guardVisitor",
  visitorManagement: "visitorManagement",
  visitorManagementHistory: "visitorManagementHistory",
  // Guard Routes
  adminHome: "adminHome",
  adminBill: "adminBill",
  adminBillOverview: "adminBillOverview",
  adminBillAdd: "adminBillAdd",
  adminBillView: "adminBillView",
  adminBillEdit: "adminBillEdit",
  adminNews: "adminNews",
  adminNewsOverview: "adminNewsOverview",
  adminNewsAdd: "adminNewsAdd",
  adminNewsView: "adminNewsView",
  adminNewsEdit: "adminNewsEdit",
  adminResidents: "adminResidents",
  adminResidentSearch: "adminResidentSearch",
  adminResidentProfile: "adminResidentProfile",
  adminResidentAdd: "adminResidentAdd",
  adminResidentEdit: "adminResidentEdit",
  adminProfile: "adminProfile",
  adminProfileOverview: "adminProfileOverview",
  adminProfileEdit: "adminProfileEdit",
};

export default routeNames;
